# Generated by Django 3.2.9 on 2021-11-11 01:53

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=512, populate_from='title', verbose_name='slug')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('body', models.TextField()),
                ('body_lang', models.CharField(choices=[('markdown', 'Markdown')], default='markdown', max_length=32)),
                ('meta', models.TextField()),
                ('meta_lang', models.CharField(choices=[('json', 'JSON')], default='json', max_length=32)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('last_edit_date', models.DateField(blank=True, null=True)),
                ('authentication', models.BooleanField(default=True)),
            ],
        ),
    ]
